# Generated by Django 5.1.2 on 2025-04-25 02:48

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="news_article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("writer", models.CharField(max_length=255)),
                ("write_date", models.DateTimeField()),
                ("category", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("url", models.CharField(max_length=200)),
                ("keywords", models.JSONField()),
                ("embedding", pgvector.django.vector.VectorField()),
            ],
        ),
    ]
