# Generated by Django 5.1.2 on 2025-04-25 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="news_article",
            new_name="Article",
        ),
    ]
