# Generated by Django 5.1.2 on 2025-05-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likehistory",
            name="liked_at",
            field=models.DateTimeField(),
        ),
    ]
