# Generated by Django 5.1.2 on 2025-05-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_likehistory_liked_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likehistory",
            name="liked_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="viewhistory",
            name="viewed_at",
            field=models.DateTimeField(),
        ),
    ]
