# Generated by Django 5.1.2 on 2025-05-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_commenthistory_delete_chatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commenthistory",
            name="commented_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
